project:
  type: website
  output-dir: docs

website:
  title: "Ben Irish"
  navbar:
    background: light
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/benirish-data
  page-footer:
    center: "© 2026 Ben Irish"
    background: light

format:
  html:
    theme: [litera, styles.css]
    toc: false
    page-layout: full
    grid:
      body-width: 900px